/////////////
// Imports //
/////////////
#import "@preview/adaptable-pset:0.2.0": *
#import "@preview/physica:0.9.8": *
#import "@preview/unify:0.8.1": *
#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#show: codly-init.with()
#codly(languages: codly-languages)

/////////////////
// Maths Setup //
/////////////////

// upright vectors
#let vectorboldupright(a) = vb($upright(#a)$)
#let vbu = vectorboldupright
#let vectorunitupright(a) = vu($upright(#a)$)
#let vuu = vectorunitupright
#let vectorarrowupright(a) = va($upright(#a)$)
#let vau = vectorarrowupright

// automatically use square brackets for vectors and matricies
#set math.vec(delim: "[")
#set math.mat(delim: "[")
#let vecrowOld = vecrow
#let vecrow = vecrowOld.with(delim: "[")

// custom units
#add-unit("decibelIsotropic", "dBi", "upright(\"dBi\")", space: true)
#add-unit("decibelWatt", "dBW", "upright(\"dBW\")", space: true)

////////////////////
// Document Setup //
////////////////////

// assignment info
#show: homework.with(
    title: "HW02 - Received Power and Link Geometry",
    author: "Vai Srivastava",
    collaborators: [],
    course-id: "ENAE694: Spacecraft Communications",
    instructor: "Prof. David Israel",
    semester: "Fall 2026",
    due-time: "September 28th. at 17:00",

    // (defaults to A4)
    paper-size: "us-letter",
)

// document settings
#set text(font: "New Computer Modern", size: 10pt)
#set enum(numbering: "a)")

// problem headings
#let probOld = prob
#let prob = prob.with(color: black)

// numerical results generated by ../src/index.py
#let s01 = read("../outputs/text/s01.txt").trim()
#let s02a = read("../outputs/text/s02a.txt").trim()
#let s02b = read("../outputs/text/s02b.txt").trim()
#let s02c = read("../outputs/text/s02c.txt").trim()

////////////////////////////
// The Assignment Itself: //
// Problems and Solutions //
////////////////////////////

#prob(title: [Slant Range #emph[(20 pts.)]])[
    A spacecraft is in a circular orbit #qty(500, "km") above Earth. Calculate its slant range from a ground station when its elevation angle is #qty(10, "degree"). Use an Earth radius of #qty(6378, "km"), neglect station altitude, and round to the nearest kilometer. Set your calculator to degrees.
] <hwk:p01>

The slant range at elevation $e$ is
$
    d = sqrt((R_E + h)^2 - R_E^2 cos^2(e)) - R_E sin(e)
$

Substituting $R_E = #qty(6378, "km")$, $h = #qty(500, "km")$, and $e = #qty(10, "degree")$ gives
$
    d &= sqrt((#qty(6378, "km") + #qty(500, "km"))^2 - (#qty(6378, "km"))^2 cos^2(#qty(10, "degree"))) \
    &quad - (#qty(6378, "km")) sin(#qty(10, "degree")) \
    &= #qty(1695.081, "km") \
    &approx #s01 #unit("km") quad qed
$

Thus, the spacecraft's slant range is #s01 #unit("km") to the nearest kilometer.

<hwk:s01>
#pagebreak(weak: true)

#prob(title: [Voyager 2 Received Power #emph[(60 pts.)]])[
    Calculate total received signal power for Voyager 2's X-band link to DSS-43, the #qty(70, "m") antenna in Canberra. Use the updated range below with radio parameters from JPL's January 1, 1996 budget @descanso-voyager[Table 5-3, p. 26].

    - Range: #qty(21476670660, "km")
    - Frequency: #qty(8.415, "GHz")
    - Transmit Power: #qty(12.3, "W")
    - Transmit Antenna Gain: #qty(48.20, "dBi")
    - Receive Antenna Gain: #qty(74.01, "dBi")

    Use #qty(0, "dB") transmit feed loss and #qty(0.42, "dB") other losses (pointing, atmosphere, and polarization combined).

    + Calculate [EIRP] in #unit("dBW"). #emph[(20 pts.)]
    <hwk:p02a>

    + Calculate free-space path loss [$"L"_"p"$] in #unit("dB"). #emph[(20 pts.)]
    <hwk:p02b>

    + Calculate received power [$"P"_"r"$] in #unit("dBW"). Round your results to one decimal place. #emph[(20 pts.)]
    <hwk:p02c>
] <hwk:p02>

First, the transmitter power in logarithmic units is

$
    [P_t] = 10 log_10((#qty(12.3, "W"))/(#qty(1, "W")))
    = #qty(10.899, "dBW")
$

+ EIRP:

    With zero transmit feed loss,
    $
        [E I R P] &= [P_t] - [L_t] + [G_t] \
        &= #qty(10.899, "dBW") - #qty(0, "dB") + #qty(48.20, "dBi") \
        &= #s02a #unit("dBW") quad qed
    $

+ Free-space path loss:

    $
        [L_p] &= #qty(92.45, "dB") + 20 log_10(21476670660) + 20 log_10(8.415) \
        &= #s02b #unit("dB") quad qed
    $

+ Received power:

    Subtracting the combined pointing, atmospheric, and polarization loss,
    $
        [P_r] &= [E I R P] - [L_p] + [G_r] - [L_"other"] \
            &= #s02a #unit("dBW") - #s02b #unit("dB") + #qty(74.01, "dBi") - #qty(0.42, "dB") \
            &= #s02c #unit("dBW") quad qed
    $

    Therefore, the total received signal power is #s02c #unit("dBW").

<hwk:s02>
#pagebreak(weak: true)

#prob(title: [The Elevation Mask Trade #emph[(20 pts.)]])[
    For the Earth-orbiting spacecraft in #link(<hwk:p01>)[Problem 1], suppose we increase the minimum elevation angle used for contacts. In two or three sentences, explain what happens to the maximum useful slant range, the worst-case free-space path loss, and the available contact time. Keep the orbit, station, frequency, and antenna gains unchanged.
] <hwk:p03>

Increasing the minimum elevation angle decreases the maximum useful slant range, so the worst-case free-space path loss during an accepted contact also decreases. However, the spacecraft spends less of each pass above the higher elevation mask, so the available contact time decreases.

<hwk:s03>
#pagebreak(weak: true)

== Code

#codly(header: [./src/index.py])
#raw(read("../src/index.py"), block: true, lang: "python") <code:index.py>

#pagebreak(weak: true)

== References

=== Formulas

#set math.equation(numbering: "(1)")

$
    d = sqrt((R_E + h)^2 - R_E^2 cos^2(e)) - R_E sin(e)
$

$
    [P] = 10 log_10 (P/(1 W))
$

$
    [E I R P] = [P_t] - [L_t] + [G_t]
$

$
    [L_p] = 92.45 + 20 log_10(R) + 20 log_10(f)
$

$
    [P_r] = [E I R P] - [L_p] + [G_r] - [L_"other"]
$

For slant range, $h$ is altitude and $e$ is elevation. In the path-loss formula, enter $R$ in #unit("km") and $f$ in #unit("GHz"). Brackets denote decibel values. Power is in #unit("dBW"), antenna gains are in #unit("dBi"), and losses are in #unit("dB"). Record losses as positive amounts and subtract them.

=== Bibliography

#bibliography("../references/literature.yaml", title: none) <ref:bibliography>
